server:
  port: 4601
  servlet:
    context-path: /clean-asistencia-horario-api

spring:
  application:
    name: clean-sueldo-beneficio
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5632/clean_rrhh_db
    username: postgres17
    password: 123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  web:
    resources:
      add-mappings: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cleanapp

constants:
  service:
    url: http://localhost:8098/translate/clean-multi-idioma

springdoc:
  api-docs:
    enabled: true
    
logging:
  level:
    org.springframework.web: DEBUG
    io.micrometer.prometheus: DEBUG
